// Manifest data loader — reads docs-manifest.json generated by `slope docs sync`
// This is the single source of truth for CLI commands, guards, MCP tools, metaphors, and roles.

// @ts-ignore — Vite handles JSON imports at build time
import manifestJson from './docs-manifest.json';

const manifest = manifestJson as any;

// Re-export typed sections from the manifest
export { manifest };
export const CLI_COMMANDS: any[] = manifest.commands;
export const GUARDS: any[] = manifest.guards;
export const MCP_TOOLS: any[] = manifest.mcpTools;
export const METAPHORS: any[] = manifest.metaphors;
export const ROLES: any[] = manifest.roles;
export const CONSTANTS: any = manifest.constants;
export const CHANGELOG: any = manifest.changelog;

// Category labels for CLI command grouping
export const CLI_CATEGORIES: Record<string, string> = {
  lifecycle: 'Sprint Lifecycle',
  scoring: 'Scoring & Review',
  analysis: 'Analysis & Reporting',
  tooling: 'Tooling & Config',
  planning: 'Planning & Roadmap',
};

// Group commands by category
export function commandsByCategory() {
  const groups: Record<string, any[]> = {};
  for (const cmd of CLI_COMMANDS) {
    const cat = cmd.category;
    if (!groups[cat]) groups[cat] = [];
    groups[cat].push(cmd);
  }
  return groups;
}
