// Manifest data loader — reads docs-manifest.json generated by `slope docs sync`
// This is the single source of truth for CLI commands, guards, MCP tools, metaphors, and roles.

import manifestJson from './docs-manifest.json';

// ── Lightweight types mirroring the manifest schema ──────────────

export interface ManifestFlag {
  flag: string;
  desc: string;
}

export interface ManifestSubcommand {
  name: string;
  desc: string;
  flags?: ManifestFlag[];
}

export interface ManifestCommand {
  cmd: string;
  desc: string;
  category: string;
  subcommands?: ManifestSubcommand[];
  flags?: ManifestFlag[];
}

export interface ManifestGuard {
  name: string;
  hookEvent: string;
  matcher?: string;
  description: string;
}

export interface ManifestToolParam {
  name: string;
  type: string;
  desc: string;
  required?: boolean;
}

export interface ManifestTool {
  name: string;
  desc: string;
  params: ManifestToolParam[];
  requiresStore: boolean;
}

export interface ManifestMetaphor {
  id: string;
  name: string;
  description: string;
  vocabulary: Record<string, string>;
  clubs?: Record<string, string>;
  shotResults?: Record<string, string>;
  hazards?: Record<string, string>;
  conditions?: Record<string, string>;
  specialPlays?: Record<string, string>;
  missDirections?: Record<string, string>;
  scoreLabels?: Record<string, string>;
  sprintTypes?: Record<string, string>;
  trainingTypes?: Record<string, string>;
  nutrition?: Record<string, string>;
}

export interface ManifestRole {
  id: string;
  name: string;
  description: string;
  focusAreas: string[];
  clubPreferences?: Record<string, string>;
  briefingFilter?: { emphasize: string[]; deemphasize: string[] };
}

// ── Typed manifest ───────────────────────────────────────────────

const manifest = (manifestJson as unknown) as {
  version: string;
  generatedAt: string;
  gitSha: string;
  checksums: Record<string, string>;
  commands: ManifestCommand[];
  guards: ManifestGuard[];
  mcpTools: ManifestTool[];
  metaphors: ManifestMetaphor[];
  roles: ManifestRole[];
  constants: Record<string, unknown>;
  changelog: { status: string; entries: unknown[] };
};

// Re-export typed sections from the manifest
export { manifest };
export const CLI_COMMANDS: ManifestCommand[] = manifest.commands;
export const GUARDS: ManifestGuard[] = manifest.guards;
export const MCP_TOOLS: ManifestTool[] = manifest.mcpTools;
export const METAPHORS: ManifestMetaphor[] = manifest.metaphors;
export const ROLES: ManifestRole[] = manifest.roles;
export const CONSTANTS = manifest.constants;
export const CHANGELOG = manifest.changelog;

// ── Training & Nutrition constants (inlined from core) ───────

export const TRAINING_TYPE_MAP: Record<string, string> = {
  research: 'driving_range',
  feedback: 'chipping_practice',
  'test-coverage': 'putting_practice',
};

export const NUTRITION_CHECKLIST: string[] = [
  'hydration',
  'diet',
  'recovery',
  'supplements',
  'stretching',
];

// ── Helpers ──────────────────────────────────────────────────

export function getMetaphor(id: string): ManifestMetaphor | undefined {
  return METAPHORS.find((m) => m.id === id);
}

// Category labels for CLI command grouping
export const CLI_CATEGORIES: Record<string, string> = {
  lifecycle: 'Sprint Lifecycle',
  scoring: 'Scoring & Review',
  analysis: 'Analysis & Reporting',
  tooling: 'Tooling & Config',
  planning: 'Planning & Roadmap',
};

// Group commands by category
export function commandsByCategory(): Record<string, ManifestCommand[]> {
  const groups: Record<string, ManifestCommand[]> = {};
  for (const cmd of CLI_COMMANDS) {
    const cat = cmd.category;
    if (!groups[cat]) groups[cat] = [];
    groups[cat].push(cmd);
  }
  return groups;
}
